#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 16, 2021 12:12:52 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import CSIEvent_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    CSIEvent_support.set_Tk_var()
    top = Toplevel1 (root)
    CSIEvent_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    CSIEvent_support.set_Tk_var()
    top = Toplevel1 (w)
    CSIEvent_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("936x618+452+147")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.007)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#e4cdd8")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.011, rely=0.016, height=33, width=86)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI Emoji} -size 10 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''BACK''')

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.233, rely=0.032, height=60, width=505)
        self.Label1.configure(background="#e4cdd8")
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold -slant italic")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''EVENT REGISTRATION''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.074, rely=0.16, height=45, width=170)
        self.Label2.configure(background="#e4cdd8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI Emoji} -size 12")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''NAME :''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.074, rely=0.239, height=45, width=170)
        self.Label3.configure(background="#e4cdd8")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI Emoji} -size 12")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''USN :''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.074, rely=0.477, height=36, width=170)
        self.Label4.configure(background="#e4cdd8")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI Emoji} -size 12")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''EVENT :''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.074, rely=0.54, height=46, width=170)
        self.Label5.configure(background="#e4cdd8")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI Emoji} -size 12")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''MEMBER :''')

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.742, rely=0.811, height=53, width=136)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#400040")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI Emoji} -size 10 -weight bold")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''SUBMIT''')

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.276, rely=0.16, height=34, relwidth=0.322)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.276, rely=0.239, height=34, relwidth=0.322)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.TCombobox1 = ttk.Combobox(self.Frame1)
        self.TCombobox1.place(relx=0.276, rely=0.477, relheight=0.056
                , relwidth=0.319)
        self.value_list = ['Event1','Event2','Event3','Event4','Event5',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=CSIEvent_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.Checkbutton2 = tk.Checkbutton(self.Frame1)
        self.Checkbutton2.place(relx=0.456, rely=0.54, relheight=0.085
                , relwidth=0.134)
        self.Checkbutton2.configure(activebackground="#ececec")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(background="#e4cdd8")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(font="-family {Segoe UI Emoji} -size 11")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''NO''')
        self.Checkbutton2.configure(variable=CSIEvent_support.che78)

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.095, rely=0.398, height=39, width=134)
        self.Label6.configure(background="#e4cdd8")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Segoe UI Emoji} -size 12")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''BRANCH :''')

        self.Entry3 = tk.Entry(self.Frame1)
        self.Entry3.place(relx=0.276, rely=0.318, height=34, relwidth=0.322)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.106, rely=0.334, height=29, width=105)
        self.Label7.configure(background="#e4cdd8")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Segoe UI Emoji} -size 11")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''SEMESTER :''')

        self.Entry4 = tk.Entry(self.Frame1)
        self.Entry4.place(relx=0.276, rely=0.398, height=34, relwidth=0.322)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Checkbutton1 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1.place(relx=0.286, rely=0.54, relheight=0.085
                , relwidth=0.119)
        self.Checkbutton1.configure(activebackground="#ececec")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#e4cdd8")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''YES''')
        self.Checkbutton1.configure(variable=CSIEvent_support.che84)

        self.Label8 = tk.Label(self.Frame1)
        self.Label8.place(relx=0.074, rely=0.621, height=37, width=170)
        self.Label8.configure(background="#e4cdd8")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(font="-family {Segoe UI Emoji} -size 11")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''AMMOUT PAID :''')

        self.Entry5 = tk.Entry(self.Frame1)
        self.Entry5.place(relx=0.276, rely=0.621, height=34, relwidth=0.322)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.Label9 = tk.Label(self.Frame1)
        self.Label9.place(relx=0.064, rely=0.718, height=26, width=180)
        self.Label9.configure(background="#e4cdd8")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(font="-family {Segoe UI Emoji} -size 11")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''PAYMENT METHOD :''')

        self.TCombobox2 = ttk.Combobox(self.Frame1)
        self.TCombobox2.place(relx=0.276, rely=0.702, relheight=0.058
                , relwidth=0.319)
        self.value_list = ['UPI','CASH',]
        self.TCombobox2.configure(values=self.value_list)
        self.TCombobox2.configure(textvariable=CSIEvent_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.Label10 = tk.Label(self.Frame1)
        self.Label10.place(relx=0.085, rely=0.781, height=45, width=162)
        self.Label10.configure(background="#e4cdd8")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(font="-family {Segoe UI Emoji} -size 11")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''CONTACT NO. :''')

        self.Entry6 = tk.Entry(self.Frame1)
        self.Entry6.place(relx=0.276, rely=0.781, height=34, relwidth=0.322)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





