#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Feb 15, 2021 05:29:27 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop53" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top68 {base} {
    global vTcl
    if {$base == ""} {
        set base .top68
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 843x658+460+180
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background #b7b7db -height 585 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 785 
    vTcl:DefineAlias "$top.fra69" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra69
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #b7b7db \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 20 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text MEMBER 
    vTcl:DefineAlias "$site_3_0.lab70" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor arrow \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 14 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BACK 
    vTcl:DefineAlias "$site_3_0.but71" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #b7b7db \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text USN: 
    vTcl:DefineAlias "$site_3_0.lab72" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent74 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 314 
    vTcl:DefineAlias "$site_3_0.ent74" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text CHECK 
    vTcl:DefineAlias "$site_3_0.but76" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Not Member? REGISTER} 
    vTcl:DefineAlias "$site_3_0.but77" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.28 -y 0 -rely 0.154 -width 0 \
        -relwidth 0.438 -height 0 -relheight 0.13 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 0 -relx 0.025 -y 0 -rely 0.051 -width 96 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.064 -y 0 -rely 0.427 -width 0 \
        -relwidth 0.257 -height 0 -relheight 0.062 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent74 \
        -in $site_3_0 -x 0 -relx 0.369 -y 0 -rely 0.427 -width 314 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but76 \
        -in $site_3_0 -x 0 -relx 0.242 -y 0 -rely 0.684 -width 126 \
        -relwidth 0 -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but77 \
        -in $site_3_0 -x 0 -relx 0.484 -y 0 -rely 0.684 -width 196 \
        -relwidth 0 -height 33 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra69 \
        -in $top -x 0 -relx 0.036 -y 0 -rely 0.061 -width 0 -relwidth 0.931 \
        -height 0 -relheight 0.889 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top68 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

