#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Feb 16, 2021 12:21:46 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop53" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top46 {base} {
    global vTcl
    if {$base == ""} {
        set base .top46
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 917x656+439+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background #b5dcfd -height 678 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 926 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #b5dcfd \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 20 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text REGISTER 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BACK 
    vTcl:DefineAlias "$site_3_0.but49" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #b5dcfd \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Name :} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #b5dcfd \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {USN :} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #b5dcfd \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Branch :} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #b5dcfd \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Year :} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #b5dcfd \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #400040 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Contact No. :} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 344 
    vTcl:DefineAlias "$site_3_0.ent55" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 344 
    vTcl:DefineAlias "$site_3_0.ent56" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 344 
    vTcl:DefineAlias "$site_3_0.ent57" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 344 
    vTcl:DefineAlias "$site_3_0.ent58" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 344 
    vTcl:DefineAlias "$site_3_0.ent60" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #400040 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Emoji} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text REGISTER 
    vTcl:DefineAlias "$site_3_0.but45" "Button2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.331 -y 0 -rely 0.088 -width 0 \
        -relwidth 0.322 -height 0 -relheight 0.128 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.039 -width 76 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.299 -width 0 \
        -relwidth 0.169 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.422 -width 0 \
        -relwidth 0.171 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.545 -width 0 \
        -relwidth 0.168 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.668 -width 0 \
        -relwidth 0.168 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.791 -width 0 \
        -relwidth 0.169 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.299 -width 344 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.422 -width 344 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.545 -width 344 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.668 -width 344 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.791 -width 344 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.896 -width 136 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -y 0 -rely -0.015 -width 0 -relwidth 1.01 -height 0 \
        -relheight 1.034 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top46 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

